AnimalAdoptionSite/Controllers/AdminAnimalController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using EntityLayer.Enums;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AnimalAdoptionSite.Controllers
{
    public class AdminAnimalController : Controller
    {
        AnimalManager am = new AnimalManager(new EfAnimalDal());

        [Authorize]
        public ActionResult Index()
        {
            var animalvalues = am.GetAnimalsList();
            return View(animalvalues);
        }
        public ActionResult Cats()
        {
            var animalvalues = am.GetAnimalsList();
            ViewBag.Cats = animalvalues.Where(x => x.AnimalBreed == AnimalBreed.Kedi).ToList();
            return View(animalvalues);
        }  public ActionResult Dogs()
        {
            var animalvalues = am.GetAnimalsList();
            ViewBag.Dogs = animalvalues.Where(x => x.AnimalBreed == AnimalBreed.Köpek).ToList();
            return View(animalvalues);
        } 
        public ActionResult Birds()
        {
            var animalvalues = am.GetAnimalsList();
            ViewBag.Birds = animalvalues.Where(x => x.AnimalBreed == AnimalBreed.Kuş).ToList();
            return View(animalvalues);
        }
        [HttpGet]
        public ActionResult AddAnimal()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAnimal(Animal p, HttpPostedFileBase AnimalImg)
        {
            //AnimalValidator animalvalidator = new AnimalValidator();
            //ValidationResult result = animalvalidator.Validate(p);
           
                if (AnimalImg != null && AnimalImg.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(AnimalImg.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                    AnimalImg.SaveAs(path);
                    p.AnimalImg = "/Images/" + fileName;
                }
                am.AnimalAdd(p);
                 return RedirectToAction("Index");
            
        }
        public ActionResult DeleteAnimal(int id)
        {
            var animalvalue = am.GetByID(id);
            am.AnimalDelete(animalvalue);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult UpdateAnimal(int id)
        {
            var animalvalue = am.GetByID(id);
            return View(animalvalue);
        }
        [HttpPost]
        public ActionResult UpdateAnimal(Animal p, HttpPostedFileBase AnimalImg)
        {
            if (AnimalImg != null && AnimalImg.ContentLength > 0)
            {
                var fileName = Path.GetFileName(AnimalImg.FileName);
                var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                AnimalImg.SaveAs(path);

                // Hayvan nesnesine fotoğraf yolunu ekleyin
                p.AnimalImg = "/Images/" + fileName;
            }


            am.AnimalUpdate(p);
            return RedirectToAction("Index");
        }

        public ActionResult ActivateAnimal(int id)
        {
            am.SetActive(id, true);
            return RedirectToAction("Index");
        }

        public ActionResult DeactivateAnimal(int id)
        {
            am.SetActive(id, false);
            return RedirectToAction("Index");
        }
    }
}

AnimalAdoptionSite/Views/AdminAnimal/AddAnimal.cshtml
@model EntityLayer.Concrete.Animal

@{
    ViewBag.Title = "AddAnimal";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}


<h1>Yeni Hayvan Ekleme Sayfası</h1>
<br />

@using (Html.BeginForm("AddAnimal", "AdminAnimal", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.LabelFor(model => model.AnimalName)
        @Html.EditorFor(model => model.AnimalName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.AnimalName, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AnimalAge)
        @Html.EditorFor(model => model.AnimalAge, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        <label for="AnimalImg">Hayvan Fotoğrafı</label>
        <input type="file" name="AnimalImg" class="form-control" />
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AnimalBreed)
        @Html.DropDownListFor(model => model.AnimalBreed, Enum.GetValues(typeof(EntityLayer.Enums.AnimalBreed)).Cast<EntityLayer.Enums.AnimalBreed>().Select(v => new SelectListItem
        {
            Text = v.ToString(),
            Value = v.ToString()
        }), "Hayvan Türü Seçiniz", new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AnimalType)
        @Html.EditorFor(model => model.AnimalType, new { htmlAttributes = new { @class = "form-control" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AnimalSex)
        @Html.DropDownListFor(model => model.AnimalSex, Enum.GetValues(typeof(EntityLayer.Enums.AnimalSex)).Cast<EntityLayer.Enums.AnimalSex>().Select(v => new SelectListItem
        {
            Text = v.ToString(),
            Value = v.ToString()
        }), "Cinsiyet Seçiniz", new { @class = "form-control" })

    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AnimalDescription)
        @Html.TextAreaFor(model => model.AnimalDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.AnimalDescription, "", new { @class = "text-danger" })
    </div>

    <br />
    <button class="btn btn-info">Kaydet</button>

}

AnimalAdoptionSite/Views/AdminAnimal/Birds.cshtml
@using EntityLayer.Concrete
@model IEnumerable<EntityLayer.Concrete.Animal>

@{
    ViewBag.Title = "Birds";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}


<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<br />
<h1 style="font-weight: bold;">Kuşlar</h1>
<br />


<table class="table table-striped">

    <tr>

        <th>ID</th>
        <th>Ad</th>
        <th>Yaş</th>
        <th>Fotoğraf</th>
        <th>Tür</th>
        <th>Cins</th>
        <th>Cinsiyet</th>
        <th>Özellik</th>
        <th>Durum</th>
        <th></th>
        <th>Güncelle</th>

    </tr>
 
  
        <!-- Similar structure for Kuşlar -->
        @foreach (var item in ViewBag.Birds as List<Animal>)
        {
            <tr>
                <td>@item.AnimalID</td>
                <td>@item.AnimalName</td>
                <td>@item.AnimalAge</td>
                <td>
                    @if (!string.IsNullOrEmpty(item.AnimalImg))
                    {
                        <img src="@item.AnimalImg" alt="@item.AnimalImg" style="width:100px; height:auto;" />
                    }
                </td>
                <td>@item.AnimalBreed</td>
                <td>@item.AnimalType</td>
                <td>@item.AnimalSex</td>
                <td>@item.AnimalDescription</td>
                <td>@(item.IsActive ? "Aktif" : "Pasif")</td>
                <td>
                    @if (item.IsActive)
                    {
                        <a href="@Url.Action("DeactivateAnimal", new { id = item.AnimalID })" class="btn btn-danger">Pasif Yap</a>
                    }
                    else
                    {
                        <a href="@Url.Action("ActivateAnimal", new { id = item.AnimalID })" class="btn btn-success">Aktif Yap</a>
                    }
                </td>
                @*<td><a href="/AdminAnimal/DeleteAnimal/@item.AnimalID" class="btn btn-danger">Sil</a></td>*@
                <td><a href="/AdminAnimal/UpdateAnimal/@item.AnimalID" class="btn btn-warning">Güncelle</a></td>
            </tr>
        }
    </table>
    <a href="/AdminAnimal/AddAnimal" class="btn btn-info">Yeni Hayvan Ekle</a>

AnimalAdoptionSite/Views/AdminAnimal/Cats.cshtml
@using EntityLayer.Concrete
@model IEnumerable<EntityLayer.Concrete.Animal>
@{
    ViewBag.Title = "Cats";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}


<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<br />
<h1 style="font-weight: bold;">Kedi</h1>
<br />


<table class="table table-striped">

    <tr>

        <th>ID</th>
        <th>Ad</th>
        <th>Yaş</th>
        <th>Fotoğraf</th>
        <th>Tür</th>
        <th>Cins</th>
        <th>Cinsiyet</th>
        <th>Özellik</th>
        <th>Durum</th>
        <th></th>
        <th>Güncelle</th>

    </tr>


    @foreach (var item in ViewBag.Cats as List<Animal>)
    {
        <tr>
            <td>@item.AnimalID</td>
            <td>@item.AnimalName</td>
            <td>@item.AnimalAge</td>
            <td>
                @if (!string.IsNullOrEmpty(item.AnimalImg))
                {
                    <img src="@item.AnimalImg" alt="@item.AnimalImg" style="width:100px; height:auto;" />
                }
            </td>
            <td>@item.AnimalBreed</td>
            <td>@item.AnimalType</td>
            <td>@item.AnimalSex</td>
            <td>@item.AnimalDescription</td>
            <td>@(item.IsActive ? "Aktif" : "Pasif")</td>
            <td>
                @if (item.IsActive)
                {
                    <a href="@Url.Action("DeactivateAnimal", new { id = item.AnimalID })" class="btn btn-danger">Pasif Yap</a>
                }
                else
                {
                    <a href="@Url.Action("ActivateAnimal", new { id = item.AnimalID })" class="btn btn-success">Aktif Yap</a>
                }
            </td>
            @*<td><a href="/AdminAnimal/DeleteAnimal/@item.AnimalID" class="btn btn-danger">Sil</a></td>*@
            <td><a href="/AdminAnimal/UpdateAnimal/@item.AnimalID" class="btn btn-warning">Güncelle</a></td>
        </tr>
    }
</table>
<br />
<a href="/AdminAnimal/AddAnimal" class="btn btn-info">Yeni Hayvan Ekle</a>

AnimalAdoptionSite/Views/AdminAnimal/Dogs.cshtml
@using EntityLayer.Concrete
@model IEnumerable<EntityLayer.Concrete.Animal>
@{
    ViewBag.Title = "Dogs";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}


<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<br />
<h1 style="font-weight: bold;">Köpek</h1>
<br />


<table class="table table-striped">

    <tr>

        <th>ID</th>
        <th>Ad</th>
        <th>Yaş</th>
        <th>Fotoğraf</th>
        <th>Tür</th>
        <th>Cins</th>
        <th>Cinsiyet</th>
        <th>Özellik</th>
        <th>Durum</th>
        <th></th>
        <th>Güncelle</th>

    </tr>


    @foreach (var item in ViewBag.Dogs as List<Animal>)
    {
        <tr>
            <td>@item.AnimalID</td>
            <td>@item.AnimalName</td>
            <td>@item.AnimalAge</td>
            <td>
                @if (!string.IsNullOrEmpty(item.AnimalImg))
                {
                    <img src="@item.AnimalImg" alt="@item.AnimalImg" style="width:100px; height:auto;" />
                }
            </td>
            <td>@item.AnimalBreed</td>
            <td>@item.AnimalType</td>
            <td>@item.AnimalSex</td>
            <td>@item.AnimalDescription</td>
            <td>@(item.IsActive ? "Aktif" : "Pasif")</td>
            <td>
                @if (item.IsActive)
                {
                    <a href="@Url.Action("DeactivateAnimal", new { id = item.AnimalID })" class="btn btn-danger">Pasif Yap</a>
                }
                else
                {
                    <a href="@Url.Action("ActivateAnimal", new { id = item.AnimalID })" class="btn btn-success">Aktif Yap</a>
                }
            </td>
            @*<td><a href="/AdminAnimal/DeleteAnimal/@item.AnimalID" class="btn btn-danger">Sil</a></td>*@
            <td><a href="/AdminAnimal/UpdateAnimal/@item.AnimalID" class="btn btn-warning">Güncelle</a></td>
        </tr>
    }
</table>
<br />
<a href="/AdminAnimal/AddAnimal" class="btn btn-info">Yeni Hayvan Ekle</a>

AnimalAdoptionSite/Views/AdminAnimal/Index.cshtml
@using EntityLayer.Concrete
@model IEnumerable<EntityLayer.Concrete.Animal>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<br />
<h1 style="font-weight: bold;">Hayvanlar</h1>
<br />


<table class="table ">

    <tr>

        <th>ID</th>
        <th>Ad</th>
        <th>Yaş</th>
        <th>Fotoğraf</th>
        <th>Tür</th>
        <th>Cins</th>
        <th>Cinsiyet</th>
        <th>Özellik</th>
        <th>Durum</th>
        <th></th>
        <th>Güncelle</th>

    </tr>
    @foreach (var item in Model)
    {

        <tr>

            <td>@item.AnimalID</td>
            <td>@item.AnimalName</td>
            <td>@item.AnimalAge</td>
            <td>
                @if (!string.IsNullOrEmpty(item.AnimalImg))
                {
                    <img src="@item.AnimalImg" alt="@item.AnimalImg" style="width:100px; height:auto;" />
                }
            </td>
            <td>@item.AnimalBreed</td>
            <td>@item.AnimalType</td>
            <td>@item.AnimalSex</td>
            <td>@item.AnimalDescription</td>

            <td>@(item.IsActive ? "Aktif" : "Pasif")</td>
            <td>
                @if (item.IsActive)
                {
                   

                <a href="@Url.Action("DeactivateAnimal", new { id = item.AnimalID })" class="btn btn-danger">Pasif Yap</a>
                }
                else
                {
                <a href="@Url.Action("ActivateAnimal", new { id = item.AnimalID })" class="btn btn-success">Aktif Yap</a>
                }
            </td>
            @*<td><a href="/AdminAnimal/DeleteAnimal/@item.AnimalID" class="btn btn-danger">Sil</a></td>*@
            <td><a href="/AdminAnimal/UpdateAnimal/@item.AnimalID" class="btn btn-warning">Güncelle</a> </td>


        </tr>

    }
</table>
<br />
<a href="/AdminAnimal/AddAnimal" class="btn btn-info"> Yeni Hayvan Ekle</a>

AnimalAdoptionSite/Views/AdminAnimal/UpdateAnimal.cshtml
@model EntityLayer.Concrete.Animal
@{
    ViewBag.Title = "UpdateAnimal";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}
<br />
<h2>Hayvan Bilgisi Güncelleme</h2>

@using (Html.BeginForm("UpdateAnimal", "AdminAnimal", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.AnimalID)

        @Html.Label("Hayvan adı")
        @Html.TextBoxFor(x => x.AnimalName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.AnimalName)
        <br />

        @Html.Label("Hayvan türü")
        @Html.TextBoxFor(x => x.AnimalBreed, new { @class = "form-control" })

        <br />
        @Html.Label("Hayvan Fotoğrafı")

        @if (!string.IsNullOrEmpty(Model.AnimalImg))
        {
            <div>
                <img src="@Url.Content(Model.AnimalImg)" alt="Hayvan Fotoğrafı" style="max-width:200px;max-height:200px;" />
            </div>
        }
        @Html.TextBoxFor(x => x.AnimalImg, new { type = "file", @class = "form-control" })
        <br />
        <br />
        @Html.Label("Hayvan yaşı")
        @Html.TextBoxFor(x => x.AnimalAge, new { @class = "form-control" })

        <br />
        @Html.Label("Hayvan cinsi")
        @Html.TextBoxFor(x => x.AnimalType, new { @class = "form-control" })

        <br />
        @Html.Label("Cinsiyet")
        @Html.TextBoxFor(x => x.AnimalSex, new { @class = "form-control" })

        <br />
        @Html.Label("Hayvan Özellikleri")
        @Html.TextBoxFor(x => x.AnimalDescription, new { @class = "form-control" })
        <br />

        <button class="btn btn-success">Güncelle</button>
    </div>
    
}