AnimalAdoptionSite/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AnimalAdoptionSite.Controllers
{
    public class AboutController : Controller
    {
        AboutManager abm= new AboutManager(new EfAboutDal());

        [Authorize]
        public ActionResult Index()

        {
            var aboutList = abm.GetList();
            return View(aboutList);
        }
                 
        [HttpGet]
        public ActionResult AddAbout()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAbout(About p)
        { 

            abm.AboutAdd(p);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteAbout(int id)
        {
            var aboutValue = abm.GetByID(id);
            abm.AboutDelete(aboutValue);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public PartialViewResult AboutPartial()
        {
            //var aboutList = abm.GetList();
            return PartialView();
        }
        public ActionResult ActivateAbout(int id)
        {
            abm.SetActive(id, true);
            return RedirectToAction("Index");
        }

        public ActionResult DeactivateAbout(int id)
        {
            abm.SetActive(id, false);
            return RedirectToAction("Index");
        }
    }
}

AnimalAdoptionSite/Views/About/AboutPartial.cshtml
@model EntityLayer.Concrete.About
<button class="btn btn-primary" data-toggle="modal" data-target="#Modal1">
    Yeni Hakkımızda Ekle
</button>

<div class="modal fade" id="Modal1" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">Hakkımızda Yazı Metin Girişi</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("AddAbout", "About", FormMethod.Post))
            {
                @Html.HiddenFor(model => model.AboutID)

                <div class="modal-body">
                    <div class="form-group">
                        <label>Biz Kimiz?</label>
                        @Html.EditorFor(model => model.AboutDetails1, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    </div>
                    <div class="form-group">
                        <label>Misyon</label>
                        @Html.EditorFor(model => model.AboutDetails2, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    </div>
                    <div class="form-group">
                        <label>Vizyon</label>
                        @Html.EditorFor(model => model.AboutDetails3, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    </div>
                    <div class="form-group">
                        <label>Ne Sunuyoruz?</label>
                        @Html.EditorFor(model => model.AboutDetails4, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    </div>
                    <button type="submit" class="btn btn-info">Kaydet</button>
                </div>
                @*<div class="modal-body">
                <div class="form-group">
                    <label>Biz Kimiz?</label>
                    <input type="text" name="AboutDetails1" class="form-control" required />
                </div>
                <div class="form-group">
                    <label>Misyon</label>
                    <input type="text" name="AboutDetails2" class="form-control" required />
                </div>
                <div class="form-group">
                    <label>Vizyon</label>
                    <input type="text" name="AboutImg1" class="form-control" required />
                </div>
                <div class="form-group">
                    <label>Ne Sunuyoruz?</label>
                    <input type="text" name="AboutImg2" class="form-control" required />
                </div>
                <button type="submit" class="btn btn-info">Kaydet</button>
            </div>*@
            }

        </div>
    </div>
</div>

@*<div class="modal" id="Modal1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Hakkımızda Yazı Metin Girişi</h2>
                </div>
                <form method="post" action="/About/AddAbout/">
                    <div class="modal-body">

                        <br />
                        <label>Biz Kimiz?</label>
                        <input type="text" name="AboutDetails1" class="form-control" />
                        <br />
                        <label>Misyon</label>
                        <input type="text" name="AboutDetails2" class="form-control" />
                        <br />
                        <label>Vizyon</label>
                        <input type="text" name="AboutImg1" class="form-control" />
                        <br />
                        <label>Ne Sunuyoruz?</label>
                        <input type="text" name="AboutImg2" class="form-control" />
                        <br />
                        <button class="btn btn-info">Kaydet</button>
                    </div>
                </form>
            </div>
        </div>
    </div>*@

AnimalAdoptionSite/Views/About/Index.cshtml
@using EntityLayer.Concrete
@model IEnumerable<EntityLayer.Concrete.About>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">

    <!-- SweetAlert JS -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        function confirmDelete(event, form) {
            event.preventDefault(); // Formun otomatik olarak gönderilmesini engeller

            Swal.fire({
                title: 'Silmek istediğinizden emin misiniz?',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#dc3545',
                cancelButtonColor: '#6c757d',
                confirmButtonText: 'Evet, sil!',
                cancelButtonText: 'Hayır, iptal et'
            }).then((result) => {
                if (result.isConfirmed) {
                    form.submit(); // Kullanıcı onaylarsa formu gönderir
                }
            });
        }
    </script>
</head>
<h1 style="font-weight: bold;">Hakkımızda Veri Listesi</h1>

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Hakkımda Başlığı</th>
        <th>Durum</th>
        <th>Aktiflik Kontrol</th>
        <th>Sil</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.AboutID</td>
            <td>Başlık</td>
            <td>@(item.IsActive ? "Aktif" : "Pasif")</td>
            <td>
                @if (item.IsActive)
                {


                    <a href="@Url.Action("DeactivateAbout", new { id = item.AboutID })" class="btn btn-danger">Pasif Yap</a>
                }
                else
                {
                    <a href="@Url.Action("ActivateAbout", new { id = item.AboutID })" class="btn btn-success">Aktif Yap</a>
                }
            </td>
            <td>
                <form action="/About/DeleteAbout/@item.AboutID" method="post" style="display:inline;" onsubmit="confirmDelete(event, this)">
                    <button type="submit" class="btn btn-danger">Sil</button>
                </form>
               

            </td>

        </tr>
    }
</table>

@Html.Action("AboutPartial", "About")